### ISSUE TITLE
Multiple entries of same month in Archives

### ISSUE THREAD

**Issue by ratulotron** [habibillah/pujangga#1]
The Archive section is supposed to show each month only once for each year. But what it really shows is the name of month as many times as the number of posts in the month. Added a screenshot to clarify.

![selection_001](https://cloud.githubusercontent.com/assets/1234482/6201216/c1274232-b4c6-11e4-8ecd-538d80874cec.png)

**Comment by habibillah** [comment]
My [sample blog](http://habibillah.kalicode.com/posts/2012/03/index.html) that use this time show the correct archive. May you explain more how to replicate this issue?

**Comment by mnzr** [comment]
Problem solved! I checked my forked version with your original one, and it seems to be missing the conditions in the [period_articles.html](https://github.com/mnzr/pujangga/blob/491249e40a61124b3f932f96b2068ec44a8f7209/templates/right-side.html) template file. Thanks a lot!

**Comment by ratulotron** [comment]
Problem solved! I checked my forked version with your original one, and it seems to be missing the conditions in the [right_side.html](https://github.com/mnzr/pujangga/blob/491249e40a61124b3f932f96b2068ec44a8f7209/templates/right-side.html) template file. Thanks a lot!
